### ISSUE TITLE
Некорректная БЭМ-нотация

### ISSUE THREAD

**Issue by nibezo** [frontgr/Cars-Fun-Site#1]
https://github.com/frontgr/Cars-Fun-Site/blob/ef1183ad489cdd9e373747c5a947acfb81438344/index.html#L11-L23

header__nav__search-input и header__nav__search - ошибка, в БЭМ-методологии [нельзя создавать элементы элементов](https://ru.bem.info/methodology/quick-start/#%D0%92%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C-1). 

Нужно создавать либо отдельный блок, либо создавать элементы header-а: 
header__search-input / header__search, и т.д., допустима _любая вложенность элементов._

**Comment by Aleksey02** [comment]
Сделал, везде поменял. если что-то не правильно, напиши, я поменяю.
Коммит - 9d405f25e9db0463be9eb8901e0c0ebfc2ed059f
