### ISSUE TITLE
Лого лучше сразу сделать ссылкой, в header/footer, на саму страницу

### ISSUE THREAD

**Issue by nibezo** [frontgr/Cars-Fun-Site#3]
https://github.com/frontgr/Cars-Fun-Site/blob/ef1183ad489cdd9e373747c5a947acfb81438344/index.html#L14

Например, вот как это сделано в ВК у лого сверху справа: 
![image](https://github.com/frontgr/Cars-Fun-Site/assets/52705623/cef1cced-23c6-4269-a326-8d065f42fd63)

**Comment by Aleksey02** [comment]
![image](https://github.com/frontgr/Cars-Fun-Site/assets/98608292/996cae7e-55bf-4197-9938-9c5d1a5a9e98)
лого из тачек тоже нужно?

**Comment by Aleksey02** [comment]
исправил - 28257c50ed03028aacc2a0cc7d529726e4c950f4
