### ISSUE TITLE
Необходимо добавить импорт файла .scss с переменными

### ISSUE THREAD

**Issue by nibezo** [frontgr/Cars-Fun-Site#7]
https://github.com/frontgr/Cars-Fun-Site/blob/a743974a157029d2dcbc7291ef99f94fe22bf195/scss/style.scss#L1-L6

+ сделать их использование в коде .scss в остальных файлах, переменные должны быть тут глобальные

**Comment by Aleksey02** [comment]
Готово - fa03bad6e2c0e56ac55445e885277641c1cad1ce
