### ISSUE TITLE
Во всех спецификациях сделать ссылки на car_info.html и поменять немного верстку

### ISSUE THREAD

**Issue by nibezo** [frontgr/Cars-Fun-Site#8]
https://github.com/frontgr/Cars-Fun-Site/blob/a743974a157029d2dcbc7291ef99f94fe22bf195/index.html#L60

тут нельзя использовать кнопку, т.к. это элемент навигации, а не функционального компонента, подробнее можно почитать в статье - https://habr.com/ru/companies/htmlacademy/articles/561892/

**Comment by Aleksey02** [comment]
Готово - d5d84e597df7d4b2a5d48235da9f34b2d01fed77
